# COMPX310 Lab 10
Alexis Manosca 1644633  
Ammia Camia 1607516

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import StratifiedKFold, GridSearchCV, cross_val_predict
from sklearn.metrics import confusion_matrix, classification_report

# ID as random seed
ID = 1607516

# Ammi's import
df = pd.read_csv('data.csv')

print("Dataset shape:", df.shape)
print("\nColumn names:")
print(df.columns.tolist())

# Checking for missing or duplicated rows
print("\nMissing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())

# Preprocessing the data
filename_col = "file"
target_col = "target"

# Handle missing target values
# df = df.dropna(subset=[target_col])

# Split the target and features
filenames = df[filename_col].copy()
X = df.drop(columns=[filename_col, target_col])
y = df[target_col].astype(int)

print("\nFeatures:", X.shape)
print("Target:", y.shape)
print("Number of classes:", (y.nunique()))
print("\nClass distribution:")
print(y.value_counts().sort_index())

# Cross validation code
cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=ID)

# To store each model's out-of-fold probabilities for the error analysis
oof_probs = {}

# Define class names once to be reused
class_names = ["mountain", "street", "buildings", "sea", "forest", "glacier"]

Dataset shape: (14034, 2050)

Column names:
['a0', 'a1', 'a2', 'a3', 'a4', 'a5', 'a6', 'a7', 'a8', 'a9', 'a10', 'a11', 'a12', 'a13', 'a14', 'a15', 'a16', 'a17', 'a18', 'a19', 'a20', 'a21', 'a22', 'a23', 'a24', 'a25', 'a26', 'a27', 'a28', 'a29', 'a30', 'a31', 'a32', 'a33', 'a34', 'a35', 'a36', 'a37', 'a38', 'a39', 'a40', 'a41', 'a42', 'a43', 'a44', 'a45', 'a46', 'a47', 'a48', 'a49', 'a50', 'a51', 'a52', 'a53', 'a54', 'a55', 'a56', 'a57', 'a58', 'a59', 'a60', 'a61', 'a62', 'a63', 'a64', 'a65', 'a66', 'a67', 'a68', 'a69', 'a70', 'a71', 'a72', 'a73', 'a74', 'a75', 'a76', 'a77', 'a78', 'a79', 'a80', 'a81', 'a82', 'a83', 'a84', 'a85', 'a86', 'a87', 'a88', 'a89', 'a90', 'a91', 'a92', 'a93', 'a94', 'a95', 'a96', 'a97', 'a98', 'a99', 'a100', 'a101', 'a102', 'a103', 'a104', 'a105', 'a106', 'a107', 'a108', 'a109', 'a110', 'a111', 'a112', 'a113', 'a114', 'a115', 'a116', 'a117', 'a118', 'a119', 'a120', 'a121', 'a122', 'a123', 'a124', 'a125', 'a126', 'a127', 'a128', 'a129', 'a130', 'a131', 'a132', 'a133', 'a134', 'a135', 'a136', 'a137', 'a138', 'a139', 'a140', 'a141', 'a142', 'a143', 'a144', 'a145', 'a146', 'a147', 'a148', 'a149', 'a150', 'a151', 'a152', 'a153', 'a154', 'a155', 'a156', 'a157', 'a158', 'a159', 'a160', 'a161', 'a162', 'a163', 'a164', 'a165', 'a166', 'a167', 'a168', 'a169', 'a170', 'a171', 'a172', 'a173', 'a174', 'a175', 'a176', 'a177', 'a178', 'a179', 'a180', 'a181', 'a182', 'a183', 'a184', 'a185', 'a186', 'a187', 'a188', 'a189', 'a190', 'a191', 'a192', 'a193', 'a194', 'a195', 'a196', 'a197', 'a198', 'a199', 'a200', 'a201', 'a202', 'a203', 'a204', 'a205', 'a206', 'a207', 'a208', 'a209', 'a210', 'a211', 'a212', 'a213', 'a214', 'a215', 'a216', 'a217', 'a218', 'a219', 'a220', 'a221', 'a222', 'a223', 'a224', 'a225', 'a226', 'a227', 'a228', 'a229', 'a230', 'a231', 'a232', 'a233', 'a234', 'a235', 'a236', 'a237', 'a238', 'a239', 'a240', 'a241', 'a242', 'a243', 'a244', 'a245', 'a246', 'a247', 'a248', 'a249', 'a250', 'a251', 'a252', 'a253', 'a254', 'a255', 'a256', 'a257', 'a258', 'a259', 'a260', 'a261', 'a262', 'a263', 'a264', 'a265', 'a266', 'a267', 'a268', 'a269', 'a270', 'a271', 'a272', 'a273', 'a274', 'a275', 'a276', 'a277', 'a278', 'a279', 'a280', 'a281', 'a282', 'a283', 'a284', 'a285', 'a286', 'a287', 'a288', 'a289', 'a290', 'a291', 'a292', 'a293', 'a294', 'a295', 'a296', 'a297', 'a298', 'a299', 'a300', 'a301', 'a302', 'a303', 'a304', 'a305', 'a306', 'a307', 'a308', 'a309', 'a310', 'a311', 'a312', 'a313', 'a314', 'a315', 'a316', 'a317', 'a318', 'a319', 'a320', 'a321', 'a322', 'a323', 'a324', 'a325', 'a326', 'a327', 'a328', 'a329', 'a330', 'a331', 'a332', 'a333', 'a334', 'a335', 'a336', 'a337', 'a338', 'a339', 'a340', 'a341', 'a342', 'a343', 'a344', 'a345', 'a346', 'a347', 'a348', 'a349', 'a350', 'a351', 'a352', 'a353', 'a354', 'a355', 'a356', 'a357', 'a358', 'a359', 'a360', 'a361', 'a362', 'a363', 'a364', 'a365', 'a366', 'a367', 'a368', 'a369', 'a370', 'a371', 'a372', 'a373', 'a374', 'a375', 'a376', 'a377', 'a378', 'a379', 'a380', 'a381', 'a382', 'a383', 'a384', 'a385', 'a386', 'a387', 'a388', 'a389', 'a390', 'a391', 'a392', 'a393', 'a394', 'a395', 'a396', 'a397', 'a398', 'a399', 'a400', 'a401', 'a402', 'a403', 'a404', 'a405', 'a406', 'a407', 'a408', 'a409', 'a410', 'a411', 'a412', 'a413', 'a414', 'a415', 'a416', 'a417', 'a418', 'a419', 'a420', 'a421', 'a422', 'a423', 'a424', 'a425', 'a426', 'a427', 'a428', 'a429', 'a430', 'a431', 'a432', 'a433', 'a434', 'a435', 'a436', 'a437', 'a438', 'a439', 'a440', 'a441', 'a442', 'a443', 'a444', 'a445', 'a446', 'a447', 'a448', 'a449', 'a450', 'a451', 'a452', 'a453', 'a454', 'a455', 'a456', 'a457', 'a458', 'a459', 'a460', 'a461', 'a462', 'a463', 'a464', 'a465', 'a466', 'a467', 'a468', 'a469', 'a470', 'a471', 'a472', 'a473', 'a474', 'a475', 'a476', 'a477', 'a478', 'a479', 'a480', 'a481', 'a482', 'a483', 'a484', 'a485', 'a486', 'a487', 'a488', 'a489', 'a490', 'a491', 'a492', 'a493', 'a494', 'a495', 'a496', 'a497', 'a498', 'a499', 'a500', 'a501', 'a502', 'a503', 'a504', 'a505', 'a506', 'a507', 'a508', 'a509', 'a510', 'a511', 'a512', 'a513', 'a514', 'a515', 'a516', 'a517', 'a518', 'a519', 'a520', 'a521', 'a522', 'a523', 'a524', 'a525', 'a526', 'a527', 'a528', 'a529', 'a530', 'a531', 'a532', 'a533', 'a534', 'a535', 'a536', 'a537', 'a538', 'a539', 'a540', 'a541', 'a542', 'a543', 'a544', 'a545', 'a546', 'a547', 'a548', 'a549', 'a550', 'a551', 'a552', 'a553', 'a554', 'a555', 'a556', 'a557', 'a558', 'a559', 'a560', 'a561', 'a562', 'a563', 'a564', 'a565', 'a566', 'a567', 'a568', 'a569', 'a570', 'a571', 'a572', 'a573', 'a574', 'a575', 'a576', 'a577', 'a578', 'a579', 'a580', 'a581', 'a582', 'a583', 'a584', 'a585', 'a586', 'a587', 'a588', 'a589', 'a590', 'a591', 'a592', 'a593', 'a594', 'a595', 'a596', 'a597', 'a598', 'a599', 'a600', 'a601', 'a602', 'a603', 'a604', 'a605', 'a606', 'a607', 'a608', 'a609', 'a610', 'a611', 'a612', 'a613', 'a614', 'a615', 'a616', 'a617', 'a618', 'a619', 'a620', 'a621', 'a622', 'a623', 'a624', 'a625', 'a626', 'a627', 'a628', 'a629', 'a630', 'a631', 'a632', 'a633', 'a634', 'a635', 'a636', 'a637', 'a638', 'a639', 'a640', 'a641', 'a642', 'a643', 'a644', 'a645', 'a646', 'a647', 'a648', 'a649', 'a650', 'a651', 'a652', 'a653', 'a654', 'a655', 'a656', 'a657', 'a658', 'a659', 'a660', 'a661', 'a662', 'a663', 'a664', 'a665', 'a666', 'a667', 'a668', 'a669', 'a670', 'a671', 'a672', 'a673', 'a674', 'a675', 'a676', 'a677', 'a678', 'a679', 'a680', 'a681', 'a682', 'a683', 'a684', 'a685', 'a686', 'a687', 'a688', 'a689', 'a690', 'a691', 'a692', 'a693', 'a694', 'a695', 'a696', 'a697', 'a698', 'a699', 'a700', 'a701', 'a702', 'a703', 'a704', 'a705', 'a706', 'a707', 'a708', 'a709', 'a710', 'a711', 'a712', 'a713', 'a714', 'a715', 'a716', 'a717', 'a718', 'a719', 'a720', 'a721', 'a722', 'a723', 'a724', 'a725', 'a726', 'a727', 'a728', 'a729', 'a730', 'a731', 'a732', 'a733', 'a734', 'a735', 'a736', 'a737', 'a738', 'a739', 'a740', 'a741', 'a742', 'a743', 'a744', 'a745', 'a746', 'a747', 'a748', 'a749', 'a750', 'a751', 'a752', 'a753', 'a754', 'a755', 'a756', 'a757', 'a758', 'a759', 'a760', 'a761', 'a762', 'a763', 'a764', 'a765', 'a766', 'a767', 'a768', 'a769', 'a770', 'a771', 'a772', 'a773', 'a774', 'a775', 'a776', 'a777', 'a778', 'a779', 'a780', 'a781', 'a782', 'a783', 'a784', 'a785', 'a786', 'a787', 'a788', 'a789', 'a790', 'a791', 'a792', 'a793', 'a794', 'a795', 'a796', 'a797', 'a798', 'a799', 'a800', 'a801', 'a802', 'a803', 'a804', 'a805', 'a806', 'a807', 'a808', 'a809', 'a810', 'a811', 'a812', 'a813', 'a814', 'a815', 'a816', 'a817', 'a818', 'a819', 'a820', 'a821', 'a822', 'a823', 'a824', 'a825', 'a826', 'a827', 'a828', 'a829', 'a830', 'a831', 'a832', 'a833', 'a834', 'a835', 'a836', 'a837', 'a838', 'a839', 'a840', 'a841', 'a842', 'a843', 'a844', 'a845', 'a846', 'a847', 'a848', 'a849', 'a850', 'a851', 'a852', 'a853', 'a854', 'a855', 'a856', 'a857', 'a858', 'a859', 'a860', 'a861', 'a862', 'a863', 'a864', 'a865', 'a866', 'a867', 'a868', 'a869', 'a870', 'a871', 'a872', 'a873', 'a874', 'a875', 'a876', 'a877', 'a878', 'a879', 'a880', 'a881', 'a882', 'a883', 'a884', 'a885', 'a886', 'a887', 'a888', 'a889', 'a890', 'a891', 'a892', 'a893', 'a894', 'a895', 'a896', 'a897', 'a898', 'a899', 'a900', 'a901', 'a902', 'a903', 'a904', 'a905', 'a906', 'a907', 'a908', 'a909', 'a910', 'a911', 'a912', 'a913', 'a914', 'a915', 'a916', 'a917', 'a918', 'a919', 'a920', 'a921', 'a922', 'a923', 'a924', 'a925', 'a926', 'a927', 'a928', 'a929', 'a930', 'a931', 'a932', 'a933', 'a934', 'a935', 'a936', 'a937', 'a938', 'a939', 'a940', 'a941', 'a942', 'a943', 'a944', 'a945', 'a946', 'a947', 'a948', 'a949', 'a950', 'a951', 'a952', 'a953', 'a954', 'a955', 'a956', 'a957', 'a958', 'a959', 'a960', 'a961', 'a962', 'a963', 'a964', 'a965', 'a966', 'a967', 'a968', 'a969', 'a970', 'a971', 'a972', 'a973', 'a974', 'a975', 'a976', 'a977', 'a978', 'a979', 'a980', 'a981', 'a982', 'a983', 'a984', 'a985', 'a986', 'a987', 'a988', 'a989', 'a990', 'a991', 'a992', 'a993', 'a994', 'a995', 'a996', 'a997', 'a998', 'a999', 'a1000', 'a1001', 'a1002', 'a1003', 'a1004', 'a1005', 'a1006', 'a1007', 'a1008', 'a1009', 'a1010', 'a1011', 'a1012', 'a1013', 'a1014', 'a1015', 'a1016', 'a1017', 'a1018', 'a1019', 'a1020', 'a1021', 'a1022', 'a1023', 'a1024', 'a1025', 'a1026', 'a1027', 'a1028', 'a1029', 'a1030', 'a1031', 'a1032', 'a1033', 'a1034', 'a1035', 'a1036', 'a1037', 'a1038', 'a1039', 'a1040', 'a1041', 'a1042', 'a1043', 'a1044', 'a1045', 'a1046', 'a1047', 'a1048', 'a1049', 'a1050', 'a1051', 'a1052', 'a1053', 'a1054', 'a1055', 'a1056', 'a1057', 'a1058', 'a1059', 'a1060', 'a1061', 'a1062', 'a1063', 'a1064', 'a1065', 'a1066', 'a1067', 'a1068', 'a1069', 'a1070', 'a1071', 'a1072', 'a1073', 'a1074', 'a1075', 'a1076', 'a1077', 'a1078', 'a1079', 'a1080', 'a1081', 'a1082', 'a1083', 'a1084', 'a1085', 'a1086', 'a1087', 'a1088', 'a1089', 'a1090', 'a1091', 'a1092', 'a1093', 'a1094', 'a1095', 'a1096', 'a1097', 'a1098', 'a1099', 'a1100', 'a1101', 'a1102', 'a1103', 'a1104', 'a1105', 'a1106', 'a1107', 'a1108', 'a1109', 'a1110', 'a1111', 'a1112', 'a1113', 'a1114', 'a1115', 'a1116', 'a1117', 'a1118', 'a1119', 'a1120', 'a1121', 'a1122', 'a1123', 'a1124', 'a1125', 'a1126', 'a1127', 'a1128', 'a1129', 'a1130', 'a1131', 'a1132', 'a1133', 'a1134', 'a1135', 'a1136', 'a1137', 'a1138', 'a1139', 'a1140', 'a1141', 'a1142', 'a1143', 'a1144', 'a1145', 'a1146', 'a1147', 'a1148', 'a1149', 'a1150', 'a1151', 'a1152', 'a1153', 'a1154', 'a1155', 'a1156', 'a1157', 'a1158', 'a1159', 'a1160', 'a1161', 'a1162', 'a1163', 'a1164', 'a1165', 'a1166', 'a1167', 'a1168', 'a1169', 'a1170', 'a1171', 'a1172', 'a1173', 'a1174', 'a1175', 'a1176', 'a1177', 'a1178', 'a1179', 'a1180', 'a1181', 'a1182', 'a1183', 'a1184', 'a1185', 'a1186', 'a1187', 'a1188', 'a1189', 'a1190', 'a1191', 'a1192', 'a1193', 'a1194', 'a1195', 'a1196', 'a1197', 'a1198', 'a1199', 'a1200', 'a1201', 'a1202', 'a1203', 'a1204', 'a1205', 'a1206', 'a1207', 'a1208', 'a1209', 'a1210', 'a1211', 'a1212', 'a1213', 'a1214', 'a1215', 'a1216', 'a1217', 'a1218', 'a1219', 'a1220', 'a1221', 'a1222', 'a1223', 'a1224', 'a1225', 'a1226', 'a1227', 'a1228', 'a1229', 'a1230', 'a1231', 'a1232', 'a1233', 'a1234', 'a1235', 'a1236', 'a1237', 'a1238', 'a1239', 'a1240', 'a1241', 'a1242', 'a1243', 'a1244', 'a1245', 'a1246', 'a1247', 'a1248', 'a1249', 'a1250', 'a1251', 'a1252', 'a1253', 'a1254', 'a1255', 'a1256', 'a1257', 'a1258', 'a1259', 'a1260', 'a1261', 'a1262', 'a1263', 'a1264', 'a1265', 'a1266', 'a1267', 'a1268', 'a1269', 'a1270', 'a1271', 'a1272', 'a1273', 'a1274', 'a1275', 'a1276', 'a1277', 'a1278', 'a1279', 'a1280', 'a1281', 'a1282', 'a1283', 'a1284', 'a1285', 'a1286', 'a1287', 'a1288', 'a1289', 'a1290', 'a1291', 'a1292', 'a1293', 'a1294', 'a1295', 'a1296', 'a1297', 'a1298', 'a1299', 'a1300', 'a1301', 'a1302', 'a1303', 'a1304', 'a1305', 'a1306', 'a1307', 'a1308', 'a1309', 'a1310', 'a1311', 'a1312', 'a1313', 'a1314', 'a1315', 'a1316', 'a1317', 'a1318', 'a1319', 'a1320', 'a1321', 'a1322', 'a1323', 'a1324', 'a1325', 'a1326', 'a1327', 'a1328', 'a1329', 'a1330', 'a1331', 'a1332', 'a1333', 'a1334', 'a1335', 'a1336', 'a1337', 'a1338', 'a1339', 'a1340', 'a1341', 'a1342', 'a1343', 'a1344', 'a1345', 'a1346', 'a1347', 'a1348', 'a1349', 'a1350', 'a1351', 'a1352', 'a1353', 'a1354', 'a1355', 'a1356', 'a1357', 'a1358', 'a1359', 'a1360', 'a1361', 'a1362', 'a1363', 'a1364', 'a1365', 'a1366', 'a1367', 'a1368', 'a1369', 'a1370', 'a1371', 'a1372', 'a1373', 'a1374', 'a1375', 'a1376', 'a1377', 'a1378', 'a1379', 'a1380', 'a1381', 'a1382', 'a1383', 'a1384', 'a1385', 'a1386', 'a1387', 'a1388', 'a1389', 'a1390', 'a1391', 'a1392', 'a1393', 'a1394', 'a1395', 'a1396', 'a1397', 'a1398', 'a1399', 'a1400', 'a1401', 'a1402', 'a1403', 'a1404', 'a1405', 'a1406', 'a1407', 'a1408', 'a1409', 'a1410', 'a1411', 'a1412', 'a1413', 'a1414', 'a1415', 'a1416', 'a1417', 'a1418', 'a1419', 'a1420', 'a1421', 'a1422', 'a1423', 'a1424', 'a1425', 'a1426', 'a1427', 'a1428', 'a1429', 'a1430', 'a1431', 'a1432', 'a1433', 'a1434', 'a1435', 'a1436', 'a1437', 'a1438', 'a1439', 'a1440', 'a1441', 'a1442', 'a1443', 'a1444', 'a1445', 'a1446', 'a1447', 'a1448', 'a1449', 'a1450', 'a1451', 'a1452', 'a1453', 'a1454', 'a1455', 'a1456', 'a1457', 'a1458', 'a1459', 'a1460', 'a1461', 'a1462', 'a1463', 'a1464', 'a1465', 'a1466', 'a1467', 'a1468', 'a1469', 'a1470', 'a1471', 'a1472', 'a1473', 'a1474', 'a1475', 'a1476', 'a1477', 'a1478', 'a1479', 'a1480', 'a1481', 'a1482', 'a1483', 'a1484', 'a1485', 'a1486', 'a1487', 'a1488', 'a1489', 'a1490', 'a1491', 'a1492', 'a1493', 'a1494', 'a1495', 'a1496', 'a1497', 'a1498', 'a1499', 'a1500', 'a1501', 'a1502', 'a1503', 'a1504', 'a1505', 'a1506', 'a1507', 'a1508', 'a1509', 'a1510', 'a1511', 'a1512', 'a1513', 'a1514', 'a1515', 'a1516', 'a1517', 'a1518', 'a1519', 'a1520', 'a1521', 'a1522', 'a1523', 'a1524', 'a1525', 'a1526', 'a1527', 'a1528', 'a1529', 'a1530', 'a1531', 'a1532', 'a1533', 'a1534', 'a1535', 'a1536', 'a1537', 'a1538', 'a1539', 'a1540', 'a1541', 'a1542', 'a1543', 'a1544', 'a1545', 'a1546', 'a1547', 'a1548', 'a1549', 'a1550', 'a1551', 'a1552', 'a1553', 'a1554', 'a1555', 'a1556', 'a1557', 'a1558', 'a1559', 'a1560', 'a1561', 'a1562', 'a1563', 'a1564', 'a1565', 'a1566', 'a1567', 'a1568', 'a1569', 'a1570', 'a1571', 'a1572', 'a1573', 'a1574', 'a1575', 'a1576', 'a1577', 'a1578', 'a1579', 'a1580', 'a1581', 'a1582', 'a1583', 'a1584', 'a1585', 'a1586', 'a1587', 'a1588', 'a1589', 'a1590', 'a1591', 'a1592', 'a1593', 'a1594', 'a1595', 'a1596', 'a1597', 'a1598', 'a1599', 'a1600', 'a1601', 'a1602', 'a1603', 'a1604', 'a1605', 'a1606', 'a1607', 'a1608', 'a1609', 'a1610', 'a1611', 'a1612', 'a1613', 'a1614', 'a1615', 'a1616', 'a1617', 'a1618', 'a1619', 'a1620', 'a1621', 'a1622', 'a1623', 'a1624', 'a1625', 'a1626', 'a1627', 'a1628', 'a1629', 'a1630', 'a1631', 'a1632', 'a1633', 'a1634', 'a1635', 'a1636', 'a1637', 'a1638', 'a1639', 'a1640', 'a1641', 'a1642', 'a1643', 'a1644', 'a1645', 'a1646', 'a1647', 'a1648', 'a1649', 'a1650', 'a1651', 'a1652', 'a1653', 'a1654', 'a1655', 'a1656', 'a1657', 'a1658', 'a1659', 'a1660', 'a1661', 'a1662', 'a1663', 'a1664', 'a1665', 'a1666', 'a1667', 'a1668', 'a1669', 'a1670', 'a1671', 'a1672', 'a1673', 'a1674', 'a1675', 'a1676', 'a1677', 'a1678', 'a1679', 'a1680', 'a1681', 'a1682', 'a1683', 'a1684', 'a1685', 'a1686', 'a1687', 'a1688', 'a1689', 'a1690', 'a1691', 'a1692', 'a1693', 'a1694', 'a1695', 'a1696', 'a1697', 'a1698', 'a1699', 'a1700', 'a1701', 'a1702', 'a1703', 'a1704', 'a1705', 'a1706', 'a1707', 'a1708', 'a1709', 'a1710', 'a1711', 'a1712', 'a1713', 'a1714', 'a1715', 'a1716', 'a1717', 'a1718', 'a1719', 'a1720', 'a1721', 'a1722', 'a1723', 'a1724', 'a1725', 'a1726', 'a1727', 'a1728', 'a1729', 'a1730', 'a1731', 'a1732', 'a1733', 'a1734', 'a1735', 'a1736', 'a1737', 'a1738', 'a1739', 'a1740', 'a1741', 'a1742', 'a1743', 'a1744', 'a1745', 'a1746', 'a1747', 'a1748', 'a1749', 'a1750', 'a1751', 'a1752', 'a1753', 'a1754', 'a1755', 'a1756', 'a1757', 'a1758', 'a1759', 'a1760', 'a1761', 'a1762', 'a1763', 'a1764', 'a1765', 'a1766', 'a1767', 'a1768', 'a1769', 'a1770', 'a1771', 'a1772', 'a1773', 'a1774', 'a1775', 'a1776', 'a1777', 'a1778', 'a1779', 'a1780', 'a1781', 'a1782', 'a1783', 'a1784', 'a1785', 'a1786', 'a1787', 'a1788', 'a1789', 'a1790', 'a1791', 'a1792', 'a1793', 'a1794', 'a1795', 'a1796', 'a1797', 'a1798', 'a1799', 'a1800', 'a1801', 'a1802', 'a1803', 'a1804', 'a1805', 'a1806', 'a1807', 'a1808', 'a1809', 'a1810', 'a1811', 'a1812', 'a1813', 'a1814', 'a1815', 'a1816', 'a1817', 'a1818', 'a1819', 'a1820', 'a1821', 'a1822', 'a1823', 'a1824', 'a1825', 'a1826', 'a1827', 'a1828', 'a1829', 'a1830', 'a1831', 'a1832', 'a1833', 'a1834', 'a1835', 'a1836', 'a1837', 'a1838', 'a1839', 'a1840', 'a1841', 'a1842', 'a1843', 'a1844', 'a1845', 'a1846', 'a1847', 'a1848', 'a1849', 'a1850', 'a1851', 'a1852', 'a1853', 'a1854', 'a1855', 'a1856', 'a1857', 'a1858', 'a1859', 'a1860', 'a1861', 'a1862', 'a1863', 'a1864', 'a1865', 'a1866', 'a1867', 'a1868', 'a1869', 'a1870', 'a1871', 'a1872', 'a1873', 'a1874', 'a1875', 'a1876', 'a1877', 'a1878', 'a1879', 'a1880', 'a1881', 'a1882', 'a1883', 'a1884', 'a1885', 'a1886', 'a1887', 'a1888', 'a1889', 'a1890', 'a1891', 'a1892', 'a1893', 'a1894', 'a1895', 'a1896', 'a1897', 'a1898', 'a1899', 'a1900', 'a1901', 'a1902', 'a1903', 'a1904', 'a1905', 'a1906', 'a1907', 'a1908', 'a1909', 'a1910', 'a1911', 'a1912', 'a1913', 'a1914', 'a1915', 'a1916', 'a1917', 'a1918', 'a1919', 'a1920', 'a1921', 'a1922', 'a1923', 'a1924', 'a1925', 'a1926', 'a1927', 'a1928', 'a1929', 'a1930', 'a1931', 'a1932', 'a1933', 'a1934', 'a1935', 'a1936', 'a1937', 'a1938', 'a1939', 'a1940', 'a1941', 'a1942', 'a1943', 'a1944', 'a1945', 'a1946', 'a1947', 'a1948', 'a1949', 'a1950', 'a1951', 'a1952', 'a1953', 'a1954', 'a1955', 'a1956', 'a1957', 'a1958', 'a1959', 'a1960', 'a1961', 'a1962', 'a1963', 'a1964', 'a1965', 'a1966', 'a1967', 'a1968', 'a1969', 'a1970', 'a1971', 'a1972', 'a1973', 'a1974', 'a1975', 'a1976', 'a1977', 'a1978', 'a1979', 'a1980', 'a1981', 'a1982', 'a1983', 'a1984', 'a1985', 'a1986', 'a1987', 'a1988', 'a1989', 'a1990', 'a1991', 'a1992', 'a1993', 'a1994', 'a1995', 'a1996', 'a1997', 'a1998', 'a1999', 'a2000', 'a2001', 'a2002', 'a2003', 'a2004', 'a2005', 'a2006', 'a2007', 'a2008', 'a2009', 'a2010', 'a2011', 'a2012', 'a2013', 'a2014', 'a2015', 'a2016', 'a2017', 'a2018', 'a2019', 'a2020', 'a2021', 'a2022', 'a2023', 'a2024', 'a2025', 'a2026', 'a2027', 'a2028', 'a2029', 'a2030', 'a2031', 'a2032', 'a2033', 'a2034', 'a2035', 'a2036', 'a2037', 'a2038', 'a2039', 'a2040', 'a2041', 'a2042', 'a2043', 'a2044', 'a2045', 'a2046', 'a2047', 'file', 'target']

Missing values: 0
Duplicate rows: 0

Features: (14034, 2048)
Target: (14034,)
Number of classes: 6

Class distribution:
target
0    2512
1    2382
2    2191
3    2274
4    2271
5    2404
Name: count, dtype: int64

## Logistic Regression

In [2]:
from sklearn.linear_model import LogisticRegression

lr_pipeline = Pipeline([("scaler", StandardScaler()), ("model", LogisticRegression(solver="lbfgs", max_iter=3000, random_state=ID))])

param_grid_lr = {
    "model__C": [0.001, 0.01, 0.1, 1, 10],
    "model__penalty": ["l2"]
}

lr_grid = GridSearchCV(lr_pipeline, param_grid_lr, cv=cv, scoring="accuracy", n_jobs=-1, verbose=1)
lr_grid.fit(X, y)

# Table of every combination tried
lr_results = pd.DataFrame(lr_grid.cv_results_)
lr_table = lr_results[["param_model__C", "param_model__penalty", "mean_test_score", "std_test_score"]]
lr_table = lr_table.sort_values("mean_test_score", ascending=False)
display(lr_table)

print("Best params:", lr_grid.best_params_)
print("Best cv accuracy:", lr_grid.best_score_)

# Out-of-fold predictions for the best setup, using the same folds
best_lr = lr_grid.best_estimator_

lr_probs = cross_val_predict(best_lr, X, y, cv=cv, method="predict_proba", n_jobs=-1)
lr_preds = lr_probs.argmax(axis=1)

# Save for the error analyis later
oof_probs["logistic"] = lr_probs

# Sanity check: these two should be almost the same
print("OOF accuracy:", (lr_preds == y).mean(), "| CV best score:", lr_grid.best_score_)

# Confusion matrix and classification report
print("Confusion matrix:")
print(confusion_matrix(y, lr_preds))

print("\nClassification report:")
print(classification_report(y, lr_preds, target_names=class_names))

Fitting 10 folds for each of 5 candidates, totalling 50 fits

c:\Users\KES\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:1381: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(

   param_model__C param_model__penalty  mean_test_score  std_test_score
0           0.001                   l2         0.942782        0.006500
1           0.010                   l2         0.937437        0.005093
2           0.100                   l2         0.930953        0.004494
3           1.000                   l2         0.928459        0.006325
4          10.000                   l2         0.924327        0.004471

Best params: {'model__C': 0.001, 'model__penalty': 'l2'}
Best cv accuracy: 0.9427816461672485
OOF accuracy: 0.9427818155907083 | CV best score: 0.9427816461672485
Confusion matrix:
[[2335    4    5   18    4  146]
 [   6 2246  124    4    2    0]
 [   3  126 2050    8    2    2]
 [  22    2    9 2228    2   11]
 [  20    1    4    3 2242    1]
 [ 218    6   14   27    9 2130]]

Classification report:
              precision    recall  f1-score   support

    mountain       0.90      0.93      0.91      2512
      street       0.94      0.94      0.94      2382
   buildings       0.93      0.94      0.93      2191
         sea       0.97      0.98      0.98      2274
      forest       0.99      0.99      0.99      2271
     glacier       0.93      0.89      0.91      2404

    accuracy                           0.94     14034
   macro avg       0.94      0.94      0.94     14034
weighted avg       0.94      0.94      0.94     14034

## k-Nearest Neighbour

In [3]:
from sklearn.neighbors import KNeighborsClassifier

# Define pipeline with scaling
knn_pipeline = Pipeline([("scaler", StandardScaler()), ("model", KNeighborsClassifier())])

param_grid_knn = {
    "model__n_neighbors": [3, 5, 7, 11, 15, 25],
    "model__weights": ["uniform", "distance"],
    "model__metric": ["euclidean", "manhattan", "cosine"]
}

knn_grid = GridSearchCV(knn_pipeline, param_grid_knn, cv=cv, scoring="accuracy", n_jobs=-1, verbose=1)
knn_grid.fit(X, y)

# Table of every combination tried
knn_results = pd.DataFrame(knn_grid.cv_results_)
knn_table = knn_results[["param_model__n_neighbors", "param_model__weights", "param_model__metric", "mean_test_score", "std_test_score"]]
knn_table = knn_table.sort_values("mean_test_score", ascending=False)
display(knn_table)

print("Best params:", knn_grid.best_params_)
print("Best cv accuracy:", knn_grid.best_score_)

# Out-of-fold predictions for the best setup, using the same folds
best_knn = knn_grid.best_estimator_

knn_probs = cross_val_predict(best_knn, X, y, cv=cv, method="predict_proba")
knn_preds = knn_probs.argmax(axis=1)

# Save for the error analysis later
oof_probs["knn"] = knn_probs

# Sanity check: these two should be almost the same
print("OOF accuracy:", (knn_preds == y).mean(), "| CV best score:", knn_grid.best_score_)

# Confusion matrix and classification report
print("Confusion matrix:")
print(confusion_matrix(y, knn_preds))

print("\nClassification report:")
print(classification_report(y, knn_preds, target_names=class_names))

Fitting 10 folds for each of 36 candidates, totalling 360 fits

,param_model__n_neighbors,param_model__weights,param_model__metric,mean_test_score,std_test_score
31,11,distance,cosine,0.928959,0.006540
17,7,distance,manhattan,0.928460,0.006646
30,11,uniform,cosine,0.928104,0.006355
18,11,uniform,manhattan,0.927889,0.006737
19,11,distance,manhattan,0.927818,0.006610
16,7,uniform,manhattan,0.927676,0.006295
33,15,distance,cosine,0.927462,0.006298
34,25,uniform,cosine,0.927177,0.005690
27,5,distance,cosine,0.927106,0.006533
35,25,distance,cosine,0.927034,0.005807
29,7,distance,cosine,0.926465,0.006957
15,5,distance,manhattan,0.926393,0.007274
32,15,uniform,cosine,0.926250,0.005999
26,5,uniform,cosine,0.926180,0.005704
14,5,uniform,manhattan,0.926037,0.005970
28,7,uniform,cosine,0.925824,0.007212
22,25,uniform,manhattan,0.925609,0.005246
23,25,distance,manhattan,0.925253,0.005614
21,15,distance,manhattan,0.925039,0.006186
20,15,uniform,manhattan,0.924683,0.006163
4,7,uniform,euclidean,0.924327,0.007927
5,7,distance,euclidean,0.924256,0.007634
7,11,distance,euclidean,0.923899,0.007665
3,5,distance,euclidean,0.923828,0.007119
25,3,distance,cosine,0.923685,0.006456
6,11,uniform,euclidean,0.923685,0.007309
24,3,uniform,cosine,0.923614,0.005961
13,3,distance,manhattan,0.923115,0.007101
12,3,uniform,manhattan,0.923044,0.006189
2,5,uniform,euclidean,0.922973,0.006571
10,25,uniform,euclidean,0.922474,0.006265
11,25,distance,euclidean,0.922260,0.006618
9,15,distance,euclidean,0.921548,0.006104
8,15,uniform,euclidean,0.921477,0.005911
1,3,distance,euclidean,0.921049,0.006568
0,3,uniform,euclidean,0.920835,0.006597

Best params: {'model__metric': 'cosine', 'model__n_neighbors': 11, 'model__weights': 'distance'}
Best cv accuracy: 0.9289589564892486
OOF accuracy: 0.9289582442639305 | CV best score: 0.9289589564892486
Confusion matrix:
[[2269    7    4   23    4  205]
 [   4 2236  129    5    8    0]
 [   4  212 1967    7    1    0]
 [  24    8   14 2216    3    9]
 [  38    6    4    4 2218    1]
 [ 218    9   10   24   12 2131]]

Classification report:
              precision    recall  f1-score   support

    mountain       0.89      0.90      0.90      2512
      street       0.90      0.94      0.92      2382
   buildings       0.92      0.90      0.91      2191
         sea       0.97      0.97      0.97      2274
      forest       0.99      0.98      0.98      2271
     glacier       0.91      0.89      0.90      2404

    accuracy                           0.93     14034
   macro avg       0.93      0.93      0.93     14034
weighted avg       0.93      0.93      0.93     14034

## Random Forest

In [4]:
from sklearn.ensemble import RandomForestClassifier

# Grid search with the same 10-fold cross validation
param_grid_rf = {
    "n_estimators": [100, 300],
    "max_depth": [None, 20],
    "max_features": ["sqrt", "log2"],
    "min_samples_leaf": [1, 2],
}

rf_grid = GridSearchCV(
    estimator=RandomForestClassifier(random_state=ID, n_jobs=-1),
    param_grid=param_grid_rf,
    cv=cv,
    scoring="accuracy",
    verbose=1,
)
rf_grid.fit(X, y)

# Table of every combination tried
rf_results = pd.DataFrame(rf_grid.cv_results_)
rf_table = rf_results[["param_n_estimators", "param_max_depth",
                       "param_max_features", "param_min_samples_leaf",
                       "mean_test_score", "std_test_score"]]
rf_table = rf_table.sort_values("mean_test_score", ascending=False)
display(rf_table)

print("Best params:", rf_grid.best_params_)
print("Best cv accuracy:", rf_grid.best_score_)

# Out-of-fold predictions for the best setup
best_rf = rf_grid.best_estimator_

rf_probs = cross_val_predict(best_rf, X, y, cv=cv, method="predict_proba")
rf_preds = np.argmax(rf_probs, axis=1)

# Save for the error analysis later
oof_probs["Random Forest"] = rf_probs

# Sanity check: these two should be almost the same
print("OOF accuracy:", (rf_preds == y).mean(), "| CV best score:", rf_grid.best_score_)

# Confusion matrix and classification report
print("\nConfusion matrix:")
print(confusion_matrix(y, rf_preds))

print("\nClassification report:")
print(classification_report(y, rf_preds, target_names=class_names))

Fitting 10 folds for each of 16 candidates, totalling 160 fits

,param_n_estimators,param_max_depth,param_max_features,param_min_samples_leaf,mean_test_score,std_test_score
1,300,None,sqrt,1,0.932664,0.005331
9,300,20,sqrt,1,0.932451,0.006534
11,300,20,sqrt,2,0.932165,0.005222
3,300,None,sqrt,2,0.931453,0.006686
13,300,20,log2,1,0.931381,0.006635
15,300,20,log2,2,0.931239,0.004580
7,300,None,log2,2,0.930597,0.004689
2,100,None,sqrt,2,0.930384,0.006294
5,300,None,log2,1,0.930099,0.007471
10,100,20,sqrt,2,0.929101,0.005717
6,100,None,log2,2,0.928887,0.006783
0,100,None,sqrt,1,0.928816,0.005024
8,100,20,sqrt,1,0.928033,0.006434
14,100,20,log2,2,0.927533,0.005519
12,100,20,log2,1,0.927248,0.006008
4,100,None,log2,1,0.926108,0.007794

Best params: {'max_depth': None, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'n_estimators': 300}
Best cv accuracy: 0.932663827817071
OOF accuracy: 0.9326635314236853 | CV best score: 0.932663827817071

Confusion matrix:
[[2369    4    2   22    6  109]
 [   6 2229  138    4    5    0]
 [   5  172 2002    9    3    0]
 [  22    2   15 2228    1    6]
 [  27    2   10    5 2227    0]
 [ 286    3   15   49   17 2034]]

Classification report:
              precision    recall  f1-score   support

    mountain       0.87      0.94      0.91      2512
      street       0.92      0.94      0.93      2382
   buildings       0.92      0.91      0.92      2191
         sea       0.96      0.98      0.97      2274
      forest       0.99      0.98      0.98      2271
     glacier       0.95      0.85      0.89      2404

    accuracy                           0.93     14034
   macro avg       0.93      0.93      0.93     14034
weighted avg       0.93      0.93      0.93     14034

## XGBoost

In [5]:
from xgboost import XGBClassifier

# Grid search with the same 10-fold cross validation
param_grid_xgb = {
    "n_estimators": [100, 300],
    "max_depth": [3, 5],
    "learning_rate": [0.01, 0.1],
    "subsample": [0.8]
}

xgb_grid = GridSearchCV(
    estimator=XGBClassifier(objective="multi:softprob", num_class=6, eval_metric="mlogloss", random_state=ID, n_jobs=-1),
    param_grid=param_grid_xgb,
    cv=cv,
    scoring="accuracy",
    verbose=1,
)

xgb_grid.fit(X, y)

# Table of every combination tried
xgb_results = pd.DataFrame(xgb_grid.cv_results_)
xgb_table = xgb_results[["param_n_estimators", "param_max_depth",
                         "param_learning_rate", "param_subsample",
                         "mean_test_score", "std_test_score"]]
xgb_table = xgb_table.sort_values("mean_test_score", ascending=False)
display(xgb_table)

print("Best params:", xgb_grid.best_params_)
print("Best cv accuracy:", xgb_grid.best_score_)

# Out-of-fold predictions for the best setup
best_xgb = xgb_grid.best_estimator_

xgb_probs = cross_val_predict(best_xgb, X, y, cv=cv, method="predict_proba")
xgb_preds = np.argmax(xgb_probs, axis=1)

# Save for the error analysis later
oof_probs["XGBoost"] = xgb_probs

# Sanity check: these two should be almost the same
print("OOF accuracy:", (xgb_preds == y).mean(), "| CV best score:", xgb_grid.best_score_)

# Confusion matrix and classification report
print("\nConfusion matrix:")
print(confusion_matrix(y, xgb_preds))

print("\nClassification report:")
print(classification_report(y, xgb_preds, target_names=class_names))

Fitting 10 folds for each of 8 candidates, totalling 80 fits

,param_n_estimators,param_max_depth,param_learning_rate,param_subsample,mean_test_score,std_test_score
7,300,5,0.10,0.8,0.940003,0.005996
5,300,3,0.10,0.8,0.939505,0.004817
6,100,5,0.10,0.8,0.935514,0.005865
4,100,3,0.10,0.8,0.933805,0.005456
3,300,5,0.01,0.8,0.924898,0.005086
1,300,3,0.01,0.8,0.914067,0.006796
2,100,5,0.01,0.8,0.912856,0.007690
0,100,3,0.01,0.8,0.894614,0.008660

Best params: {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 300, 'subsample': 0.8}
Best cv accuracy: 0.9400034622593424
OOF accuracy: 0.9400028502208921 | CV best score: 0.9400034622593424

Confusion matrix:
[[2355    3    4   19    6  125]
 [   6 2246  125    2    3    0]
 [   5  145 2031    8    1    1]
 [  24    4   11 2221    2   12]
 [  21    3    5    4 2237    1]
 [ 244   10    9   27   12 2102]]

Classification report:
              precision    recall  f1-score   support

    mountain       0.89      0.94      0.91      2512
      street       0.93      0.94      0.94      2382
   buildings       0.93      0.93      0.93      2191
         sea       0.97      0.98      0.98      2274
      forest       0.99      0.99      0.99      2271
     glacier       0.94      0.87      0.91      2404

    accuracy                           0.94     14034
   macro avg       0.94      0.94      0.94     14034
weighted avg       0.94      0.94      0.94     14034

## Fully Connected Neural Network (FCNN)

In [6]:
from sklearn.neural_network import MLPClassifier

# Defines the pipeline - scales the data first then goes into the neural network
nn_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("mlp", MLPClassifier(
        max_iter=300,
        early_stopping=True,
        random_state=ID,
    )),
])

# Defines the grid
param_grid_nn = {
    "mlp__hidden_layer_sizes": [(128,), (256,), (128, 64)],
    "mlp__alpha": [0.0001, 0.001, 0.01], # Regularisation strength
    "mlp__epsilon": [1e-8, 1e-6, 1e-4],
}

# Grid search - tries every combination and runs cross validation for each one
nn_grid = GridSearchCV(
    estimator=nn_pipeline,
    param_grid=param_grid_nn,
    cv=cv,
    scoring="accuracy",
    n_jobs=-1,
    verbose=1,
)
nn_grid.fit(X, y)

# Display the results
nn_results = pd.DataFrame(nn_grid.cv_results_)
nn_table = nn_results[["param_mlp__hidden_layer_sizes", "param_mlp__alpha",
                       "param_mlp__epsilon", "mean_test_score", "std_test_score"]]
nn_table = nn_table.sort_values("mean_test_score", ascending=False)
display(nn_table)

print("Best params:", nn_grid.best_params_)
print("Best cv accuracy:", nn_grid.best_score_)

# Display the best model and its predictions
best_nn = nn_grid.best_estimator_

nn_probs = cross_val_predict(best_nn, X, y, cv=cv, method="predict_proba")
nn_preds = np.argmax(nn_probs, axis=1)

# Save for the error analysis later
oof_probs["Neural Network"] = nn_probs

# Sanity check: these two should be almost the same
print("OOF accuracy:", (nn_preds == y).mean(), "| CV best score:", nn_grid.best_score_)

# Display confusion matrix and classification report
print("\nConfusion matrix:")
print(confusion_matrix(y, nn_preds))

print("\nClassification report:")
print(classification_report(y, nn_preds, target_names=class_names))

Fitting 10 folds for each of 27 candidates, totalling 270 fits

,param_mlp__hidden_layer_sizes,param_mlp__alpha,param_mlp__epsilon,mean_test_score,std_test_score
22,"(256,)",0.0100,1.000000e-06,0.938150,0.005793
4,"(256,)",0.0001,1.000000e-06,0.938007,0.005731
6,"(128,)",0.0001,1.000000e-04,0.937865,0.007014
0,"(128,)",0.0001,1.000000e-08,0.937795,0.006828
21,"(128,)",0.0100,1.000000e-06,0.937794,0.006012
3,"(128,)",0.0001,1.000000e-06,0.937723,0.006511
18,"(128,)",0.0100,1.000000e-08,0.937723,0.005890
19,"(256,)",0.0100,1.000000e-08,0.937722,0.006760
8,"(128, 64)",0.0001,1.000000e-04,0.937580,0.004627
17,"(128, 64)",0.0010,1.000000e-04,0.937295,0.004302
24,"(128,)",0.0100,1.000000e-04,0.937153,0.006720
12,"(128,)",0.0010,1.000000e-06,0.937153,0.007039
23,"(128, 64)",0.0100,1.000000e-06,0.937152,0.005091
9,"(128,)",0.0010,1.000000e-08,0.937011,0.006030
1,"(256,)",0.0001,1.000000e-08,0.937010,0.005372
5,"(128, 64)",0.0001,1.000000e-06,0.937010,0.004720
13,"(256,)",0.0010,1.000000e-06,0.936938,0.005526
15,"(128,)",0.0010,1.000000e-04,0.936868,0.007957
26,"(128, 64)",0.0100,1.000000e-04,0.936868,0.005824
14,"(128, 64)",0.0010,1.000000e-06,0.936868,0.004877
7,"(256,)",0.0001,1.000000e-04,0.936725,0.003862
20,"(128, 64)",0.0100,1.000000e-08,0.936369,0.004476
11,"(128, 64)",0.0010,1.000000e-08,0.936084,0.004537
25,"(256,)",0.0100,1.000000e-04,0.936084,0.003677
10,"(256,)",0.0010,1.000000e-08,0.935941,0.007260
16,"(256,)",0.0010,1.000000e-04,0.935870,0.004937
2,"(128, 64)",0.0001,1.000000e-08,0.935799,0.004888

Best params: {'mlp__alpha': 0.01, 'mlp__epsilon': 1e-06, 'mlp__hidden_layer_sizes': (256,)}
Best cv accuracy: 0.9381496305231158
OOF accuracy: 0.9381502066410147 | CV best score: 0.9381496305231158

Confusion matrix:
[[2326    4    4   21    5  152]
 [   3 2237  133    5    2    2]
 [   4  130 2043   10    2    2]
 [  24    4   15 2212    1   18]
 [  19    0    2    2 2248    0]
 [ 253    7   10   25    9 2100]]

Classification report:
              precision    recall  f1-score   support

    mountain       0.88      0.93      0.90      2512
      street       0.94      0.94      0.94      2382
   buildings       0.93      0.93      0.93      2191
         sea       0.97      0.97      0.97      2274
      forest       0.99      0.99      0.99      2271
     glacier       0.92      0.87      0.90      2404

    accuracy                           0.94     14034
   macro avg       0.94      0.94      0.94     14034
weighted avg       0.94      0.94      0.94     14034

## My Conclusions

**What we learnt**

---

**Best parameter combination found**

---

**Observation about `C`**

---

**One thing that surprised us or differed from initial prediction**

---

**One limitation of this experiment**

---